version: '3.4'

services:
  db:
    image: mysql:8.0.32
    volumes:
      - ~/projects/blogDb:/var/lib/mysql
    ports:
      - "3306:3306"

  todoapi:
    build: .
    ports:
      - 5001:5000
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5000
    depends_on:
      - db